### PR TITLE
Use `overlay0` for decoration lines

### PR DESCRIPTION
**Pull request by sumit-sahrawat**
This PR updates the color schemes to use `overlay0` to draw decoration lines (for boxes, underline, etc.) which is more in line with the [catppuccin guidelines](https://github.com/catppuccin/catppuccin/blob/b3584ebc7a74fed37bd7d0dda494d88c17248439/docs/style-guide.md#terminals) (README screenshot below)

Screenshot 2024-12-31 at 22 49 53

## Preview

preview

### CODE REVIEW

**Comment by sumit-sahrawat** [comment]
I added a `bold` to `commit-decoration-style` for checking how it looks and ended up leaving it in. Can remove it if it's not desirable.

**Comment by Anomalocaridid** [comment]
LGTM! Definitely an improvement. Also thanks for updating the previews.

Would you mind adding a [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) type such as `fix:` to the beginning of your commit?

**Comment by sumit-sahrawat** [comment]
> LGTM! Definitely an improvement. Also thanks for updating the previews.
> 
> Would you mind adding a [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) type such as `fix:` to the beginning of your commit?

Updated as suggested. Thanks for the review @Anomalocaridid!

**Review by Anomalocaridid — APPROVED** [review]

**Comment by Anomalocaridid** [comment]
Thank you!

**Pull request merged**
